# Generated by Django 5.2.7 on 2025-11-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicant_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='nota',
        ),
    ]
