# Generated by Django 5.2.7 on 2025-11-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_applicant_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoexterno',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Contrato externo', 'verbose_name_plural': 'Contratos externos'},
        ),
        migrations.AlterUniqueTogether(
            name='contratoexterno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='detalle_artefacto',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Detalle de embarcación'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_externos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='tipo_artefacto',
            field=models.CharField(blank=True, choices=[('BOTE', 'Bote'), ('LANCHA', 'Lancha'), ('MOTO_AGUA', 'Moto de agua'), ('OTRO', 'Otro')], default='OTRO', max_length=20, null=True, verbose_name='Tipo de embarcación'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un solicitante con este email.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Ya existe un solicitante con este RUT.'}, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='apellido',
            field=models.CharField(max_length=80, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='licencia_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='licencia_validada',
            field=models.BooleanField(default=False, help_text='Marcar cuando el supervisor confirma que la licencia es válida'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='licencia_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_externos', to='accounts.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.RemoveField(
            model_name='contratoexterno',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='contratoexterno',
            name='firma',
        ),
    ]
