# Generated by Django 5.2.7 on 2025-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_contratoexterno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
