# Generated by Django 5.2.7 on 2025-11-16 18:48

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_foto_userprofile_last_username_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoexterno',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='contratoexterno',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contratoexterno',
            name='rut',
            field=models.CharField(max_length=20, validators=[accounts.validators.validar_rut_formato], verbose_name='RUT'),
        ),
    ]
