# Generated by Django 5.2.7 on 2025-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contratoexterno_direccion_contratoexterno_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
