# Generated by Django 5.2.7 on 2025-10-16 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(default='LIBRE', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userprofile')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('override_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('LANCHA', 'Lancha'), ('YATE', 'Yate'), ('MOTO', 'Moto de agua')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='embarcaciones/')),
                ('amarra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.amarra')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarcaciones', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_SALIDA', 'En salida'), ('EN_ARRIBO', 'En arribo'), ('CERRADO', 'Cerrado')], default='SOLICITADO', max_length=12)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('tolerancia_min', models.PositiveIntegerField(default=0)),
                ('hora_arribo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.embarcacion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
        ),
    ]
