# Generated by Django 5.2.7 on 2025-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nota',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pasajeros',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
